default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: teacher_courses_proposals_development
  username: <%= Rails.application.credentials.username! %>
  password: <%= Rails.application.credentials.password! %>
  host: <%= Rails.application.credentials.host! %>
  port: <%= Rails.application.credentials.port! %>

test:
  <<: *default
  database: teacher_courses_proposals_test
  username: <%= Rails.application.credentials.username! %>
  password: <%= Rails.application.credentials.password! %>
  host: <%= Rails.application.credentials.host! %>
  port: <%= Rails.application.credentials.port! %>

production:
  <<: *default
  database: teacher_courses_proposals_production
  username: teacher_courses_proposals
  password: <%= ENV['TEACHER_COURSES_PROPOSALS_DATABASE_PASSWORD'] %>
